import * as Checkbox from './components/Checkbox/Checkbox.stories'
import * as Link from './components/Link/Link.stories'
import * as MobileNavIsland from './components/MobileNavIsland/MobileNavIsland.stories'
import * as PrimaryButton from './components/PrimaryButton/PrimaryButton.stories'
import * as Quiz from './components/Quiz/Quiz.stories'
import * as Sandbox from './components/Sandbox/Sandbox.stories'
import * as SubscribeButton from './components/SubscribeButton/SubscribeButton.stories'
import * as SvgGridWrapper from './components/SvgGridWrapper/SvgGridWrapper.stories'
import * as Visualizer from './components/Visualizer/Visualizer.stories'
export const stories = [{ name: `components`, stories: [{ name: 'Checkbox', variants: Checkbox },{ name: 'Link', variants: Link },{ name: 'MobileNavIsland', variants: MobileNavIsland },{ name: 'PrimaryButton', variants: PrimaryButton },{ name: 'Quiz', variants: Quiz },{ name: 'Sandbox', variants: Sandbox },{ name: 'SubscribeButton', variants: SubscribeButton },{ name: 'SvgGridWrapper', variants: SvgGridWrapper },{ name: 'Visualizer', variants: Visualizer }] }];